### ISSUE TITLE
习题答案错误

### ISSUE THREAD

**Issue by Yegezw** [Hansimov/asm-lang#1]
https://hansimov.gitbook.io/asm-lang/solutions/ch03-registers-memory-access#jian-ce-dian-3.2
第 3 章：寄存器（内存访问）
检测点 3.2
（2）补全下面的程序，使其可以将 10000H\~1000FH 中的 8 个宇，逆序复制到 20000H\~2000FH 中 。

![problem](https://user-images.githubusercontent.com/82441492/187033651-42c1ae06-13e5-4c7f-940e-b24e73e8bcfa.png)

**Comment by Hansimov** [comment]
@Yegezw 谢谢指正，两处 `ds` 均已修改为 `ss`。
